### ISSUE TITLE
It's not possible to change a Work Center Code in a "Prod. Order Routing"

### ISSUE THREAD

**Issue by rwe12345** [microsoft/BCApps#1719] opened 2024-07-22 09:02 UTC
Please include the following with each issue:

**1. Describe the bug**
If you created a new production order and you want to change the work center code (or machine code) on an production order routing you will get an error message.

**2. To Reproduce**
-	Create a release production order for a item with a routing.
-	Refresh the production order
-	In the production order routing you will see the work centers of the routing
![image](https://github.com/user-attachments/assets/9e870cc6-aade-4fe9-9364-de8677597087)
-	Change a work center code
-	Then you get the next error message
![image](https://github.com/user-attachments/assets/c2dd2877-0d09-4aed-a7cf-9ca84f428340)

**3. Expected behavior**
I expected that it's possible to change the work center code without error message.

**4. Actual behavior**
In the current version you will get an error message.
![image](https://github.com/user-attachments/assets/9c4b82cd-af6a-4c0f-9f4d-5b3e2ebb5de6)

**5. Versions:**
BC24.3
Location of the error message
codeunit 99000772 "Prod. Order Route Management"
procedure SetRtngLineSequenceForward
![image](https://github.com/user-attachments/assets/17c4b9c8-5795-41ef-ba6a-f122227caaba)

**Comment by JesperSchulz** [comment] 2024-08-26 13:15
@rwe12345, your issue was transferred here to BCApps, where you can create PRs to address the issues you've found yourself. Is that something you'd be interested in, or do you want Microsoft to look into the issue for you? In that case, you need to create a support case.

**Comment by pmohanakrishna** [comment] 2024-08-30 07:25
@rwe12345 I tried to reproduce on 24.4 and couldn't. Please check once again on the 24.4 version.

**Comment by JesperSchulz** [comment] 2024-09-13 08:12
I guess there's no issue after all then. Closing issue.
If the issue is valid after all, please either create a support case to have the Business Central team fix it, or create a new issue if you'd like to address the issue yourself. Since the code you are referring to is in the BaseApp, you'd have to suggest and fix this code in the BaseApp contribution pilot: https://github.com/microsoft/businesscentralapps. For access to the pilot, please fill out the following form: https://forms.office.com/r/E9wyE5a58f.

**Closed by JesperSchulz** 2024-09-13 08:12 UTC
Labels: Follow Up
