### ISSUE TITLE
[BC Idea]: Create Wrapper for ErrorInfo to make it easier to create ErrorInfos

### ISSUE THREAD

**Issue by StefanMaron** [microsoft/BCApps#1484] opened 2024-07-04 06:00 UTC
### BC Idea Link

https://experience.dynamics.com/ideas/idea/?ideaid=7e612f35-ac3d-ef11-a295-000d3a059b20

### Description

I often find myself raising errors the "old way with Error('some error message'); just because its so much easier to type.

The idea is to create a wrapper codeunit with all the procedures build in a way that every aspect of the ErrorInfo type is optional via parameters, and every function will return the ErrorInfo type. 

That way we can easily create an ErrorInfo object inline without the need to create long functions.

Example:

```AL
Error(
    ErrorInfo.Create()
        .Message('Something went wrong')
        .SetTableId(Database::MyTable)
        .AddNavigationAction('ShowMe')
        .AddAction('FixIt',Codeunit::FixErrorHelper, 'FixTheError')
);
```

For complex scenarios, this wont improve readability of course, and its not the intention of course, its more to make it easier to uptake ErrorInfo more easily.

### I will provide the implementation for this BC Idea

- [X] I will provide the implementation for this BC Idea
Internal work item: [AB#540968](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540968)

**Comment by guidorobben** [comment] 2024-07-04 14:27
Great idea.

**Comment by StefanMaron** [comment] 2024-07-04 17:20
I created an implementation for this already:

https://github.com/StefanMaron/ErrorInfoWrapper

**Comment by guidorobben** [comment] 2024-07-04 17:57
Looks great on first sight.

**Comment by StefanSosic** [comment] 2024-07-08 21:54
@StefanMaron Please update the Issue name with name of BC Idea, currently its empty

**Comment by StefanMaron** [comment] 2024-07-09 04:33
Thanks @StefanSosic did not notice that.

**Comment by JesperSchulz** [comment] 2024-08-06 14:38
@StefanMaron, there is indeed something wrong with the idea. Could you maybe try to recreate that one?

**Comment by StefanMaron** [comment] 2024-08-06 15:02
@JesperSchulz I did twice, and it keeps disappearing, am not sure what I am doing wrong

**Comment by JesperSchulz** [comment] 2024-08-09 11:19
> @JesperSchulz I did twice, and it keeps disappearing, am not sure what I am doing wrong

Seems like we're having an internal problem with the ideas site: https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=2871035285200896.

We're looking into it! Sorry about the inconveinience!

**Comment by JesperSchulz** [comment] 2024-08-09 11:31
Your idea is now active - for now! Let's see for how long 🤣 We're still investigating the root cause.

**Comment by StefanMaron** [comment] 2024-08-12 11:21
Thanks! Is this now something I will need to collect votes for? Or can I go ahead and create the PR?

**Comment by JesperSchulz** [comment] 2024-08-16 15:58
Update: We're investigating if this should get fixed in the application, or if this would be a candidate for the language.

**Comment by StefanMaron** [comment] 2024-08-16 17:10
Language 💯 if possible :)

**Comment by JesperSchulz** [comment] 2024-08-26 13:11
The attached workitem was moved to the Developer Tools team's backlog 🙂 This will be made part of the language, when time allows!
Allow me to close this issue for now, as this won't result in a GitHub PR.

**Closed by JesperSchulz** 2024-08-26 13:11 UTC
Labels: BCIdea, Follow Up, Linked
