### ISSUE TITLE
[Bug]: AFS ListDirectory errors if folder empty

### ISSUE THREAD

**Issue by ikickicts** [microsoft/BCApps#1535] opened 2024-07-10 07:09 UTC
### Describe the issue

Within the Azure File Services API an error occurs when reading the contents of an empty folder.

The AFS Directory Content does not exists. Identification fields and values: Entry No: '0'

The issue appears to be in the ListDirectory function of the AFS File Client Impl codeunit. It attempts to read the contents of a folder into the AFS Directory Content, then it updates the "Next Marker" field on the record before modifying. If the folder is empty, then the AFS Directory Content record does not exist, so the Modify fails

This issue only started occurring in BC24.2

### Expected behavior

Calling the ListDirectory function should not error if the folder is empty.

### Steps to reproduce

Using the AFS File Client codeunit, call the ListDirectory function, passing in the name of the folder to read, and the AFS DirectoryContent table

        FromAFSFileClient.Initialize(AzureStorageSetup."Account Name", FileShare, Authorization);

        if FilePrefix <> '' then begin
            AFSOptionalParameters.Prefix(FilePrefix);
            AFSOperationResponse := FromAFSFileClient.ListDirectory(FolderName, true, TempAFSDirectoryContent, AFSOptionalParameters);
        end else
            AFSOperationResponse := FromAFSFileClient.ListDirectory(FolderName, TempAFSDirectoryContent);
        if not AFSOperationResponse.IsSuccessful() then
            Error(Format(AFSOperationResponse.GetError()));

If the folder is not empty, then the list of files is returned in the TempADSDirectoryContent table. If the folder is empty, the error occurs

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by DennyHW** [comment] 2024-07-24 13:02
Please fix it ASAP even in v. 24.4 because is blocking a lot of custom features.
The error also occurs if I try to get the content list of an empty directory (without files inside)

**Comment by JesperSchulz** [comment] 2024-08-26 08:41
@ikickicts, you suggested that you will add a fix for this issue. Is that still the plan?

**Comment by DennyHW** [comment] 2024-08-26 10:38
This fix has been applied in BC25 build only.

Fixes https://github.com/microsoft/BCApps/issues/1409

Fixes
[AB#540616](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540616)

![immagine](https://github.com/user-attachments/assets/42a9c475-c557-48e0-9702-0e6472b1a5db)

![immagine](https://github.com/user-attachments/assets/def719cd-463f-4ab8-8876-660f3bbc33a7)

**Comment by JesperSchulz** [comment] 2024-08-27 07:36
> This fix has been applied in BC25 build only.
> 
> Fixes #1409
> 
> Fixes [AB#540616](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540616)
> 
> ![immagine](https://private-user-images.githubusercontent.com/53569676/361404480-42a9c475-c557-48e0-9702-0e6472b1a5db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDQzMDQsIm5iZiI6MTcyNDc0NDAwNCwicGF0aCI6Ii81MzU2OTY3Ni8zNjE0MDQ0ODAtNDJhOWM0NzUtYzU1Ny00OGUwLTk3MDItMGU2NDcyYjFhNWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA3MzMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNzYzZmY2YjE4NmVkMGFhZDU3ZTdjM2UyOWRiZGU2YmM2NWU3ZjUwODdjNTAzNTRlMWQ0NzRjMmY3YjY0ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JvmJclVCd94LoeFK0TOEMOKD6MJxVGsotPyO0ea1Ouw)
> 
> ![immagine](https://private-user-images.githubusercontent.com/53569676/361404595-def719cd-463f-4ab8-8876-660f3bbc33a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDQzMDQsIm5iZiI6MTcyNDc0NDAwNCwicGF0aCI6Ii81MzU2OTY3Ni8zNjE0MDQ1OTUtZGVmNzE5Y2QtNDYzZi00YWI4LTg4NzYtNjYwZjNiYmMzM2E3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA3MzMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0NjhiZWM3MjljNmZkMzQ3MTQ4NjQzMWRiOTQzNjUyZDY1M2FmMmIwMTMxYjQ1ZTY5MmY2N2U4ODNkYmQ3ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7R_pvqZiXIN061rXGIbUzy40beI2D6rSknF0XAnTXDk)
> 
> Same issue, same solution.

Thanks a lot, @DennyHW! Great that you're able to help keeping the overview 💪 In that case I will close this issue as a duplicate of #1409.
At this point there's little sense in backporting, as the next release train I can jump on anyway is version 25 in October. The september one is a wrap.

**Closed by JesperSchulz** 2024-08-27 07:36 UTC
Labels: Bug, Approved

**Comment by DennyHW** [comment] 2024-08-27 07:44
Yes, but with the new policy in upgrade timeline, some environments may be upgraded in 5 months starting from October. Please backport the fix.

I remember thar 24.0 had no issue.
The issue was introduced in 24.2 but fixed only on 25.x.

It's one line of code... please consider backporting.

**Comment by JesperSchulz** [comment] 2024-08-27 07:48
I'll see what I can do. Maybe I can squeeze it into 24.5, as no strings were changed.

**Comment by JesperSchulz** [comment] 2024-08-27 08:06
Here you go: https://github.com/microsoft/BCApps/pull/1886
